package com.getprepared.utils;

import java.sql.Connection;
import java.sql.PreparedStatement;

import static com.getprepared.utils.SqlCallable.call;
import static com.getprepared.utils.SqlRunnable.run;

/**
 * Created by koval on 05.01.2017.
 */
public class ConnectionUtils {

    private ConnectionUtils() { }

    public static void commit(final Connection con) {
        run(con::commit, "Failed to commit connection");
    }

    public static void rollback(final Connection con) {
        run(con::rollback , "Failed to rollback connection");
    }

    public static void setAutoCommit(final Connection con, final boolean autoCommit) {
        run(() -> con.setAutoCommit(autoCommit) , "Failed to setAutoCommitFalse");
    }

    public static PreparedStatement prepareStatement(final Connection con, final String sql) {
        return call(() -> con.prepareStatement(sql), "Failed to get PreparedStatement");
    }

    public static PreparedStatement prepareStatement(final Connection con, final String sql,
                                                     final int autoGeneratedKeys) {
        return call(() -> con.prepareStatement(sql, autoGeneratedKeys), "Failed to get PreparedStatement");
    }

    public static void close(final Connection con) {
        run(con::close, "Failed to close");
    }
}
